# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            MongoDB Perú
tagline:          'Jekyll Theme'
description:      'Grupo de usuarios de MongoDB Perú'
url:              http://mongodbperu.com

author:
  name:           'MongoDB Perú'
  url:            https://twitter.com/mongodbperu

paginate:         5

# Custom vars

github:
  repo:           https://github.com/MongoDBPeru/mongodbperu.github.io